### ISSUE TITLE
Have donate 25xrb

### ISSUE THREAD

**Issue by soliury** [frankh/rai#1]
good job, wish you can keep going.

just donated 25xrb, txid: https://raiblocks.net/block/index.php?h=627A66C3FC79702D365146AEABACF7AA037E02DA5FA32A85D9C14A94F3DC7530

**Comment by brendancsmith** [comment]
Awesome! Big thanks to both of you for making the XRB community better.

**Comment by frankh** [comment]
Thanks a lot!
